"""change tax, phone column and add parent_tax

Revision ID: 389718915a7d
Revises: 6c97a4393e14
Create Date: 2023-09-09 14:39:16.894306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '389718915a7d'
down_revision: Union[str, None] = '6c97a4393e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', column_name= 'phone')
    op.add_column('Users', sa.Column('parent_tax', sa.Integer(), nullable=True))


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('phone', sa.Integer(), nullable=True))
    op.drop_column('Users', column_name= 'parent_tax')

    # ### end Alembic commands ###
