"""empty message

Revision ID: 6c97a4393e14
Revises: 7bebc521fde4
Create Date: 2023-09-06 15:30:53.250373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c97a4393e14'
down_revision: Union[str, None] = '7bebc521fde4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Approve_requests', sa.Column('tax', sa.Integer(), nullable=True))
    op.add_column('Approve_requests', sa.Column('address', sa.String(), nullable=True))
    op.add_column('Approve_requests', sa.Column('legal_representative', sa.String(), nullable=True))
    op.add_column('Approve_requests', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Approve_requests', sa.Column('tax', sa.Integer(), nullable=True))
    op.drop_column('Approve_requests', sa.Column('address', sa.String(), nullable=True))
    op.drop_column('Approve_requests', sa.Column('legal_representative', sa.String(), nullable=True))
    op.drop_column('Approve_requests', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
