"""add column email in table ApproveRequest

Revision ID: 8afebb7d4dd1
Revises: a53123678ea0
Create Date: 2023-09-19 11:34:58.055174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8afebb7d4dd1'
down_revision: Union[str, None] = 'a53123678ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Approve_requests', sa.Column('email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(table_name = 'Approve_requests', column_name = 'email')
    # ### end Alembic commands ###
